### ISSUE TITLE
Not possible to view Data for some tested URLs (2.0.1)

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe-android#192] opened 2019-02-04 23:01 UTC
In the latest OONI Probe 2.0.1 on Android, I am not able to view the Data for some tested URLs.

When I click menu icon => Data (for aidsonline.com, for example), it takes me back to the page listing the tested URLs, instead of showing the raw network measurement data. 

This is not the case for most tested URLs, but only for a few.

**Comment by elioqoshi** [comment] 2019-02-09 18:40
@bassosimone @xanscale is there something we can do to reproduce this? I haven't encountered this myself on any test on my Android phone (One Plus 6)

**Comment by elioqoshi** [comment] 2019-03-05 14:22
@agrabeli we need to have some more context in order to see if we can reproduce it (or even you)

**Comment by lorenzoPrimi** [comment] 2019-11-22 08:56
@agrabeli does this still happen?

**Comment by hellais** [comment] 2019-11-22 15:45
This may either be a dupe of: https://github.com/ooni/probe-android/issues/241 or https://github.com/ooni/probe/issues/865, unless it's something else, but we need more information on how to reproduce.

Closing the issue, please open another one if you find a way to reproduce.

**Closed by hellais** 2019-11-22 15:45 UTC
Labels: bug, cannot_reproduce_bug, invalid, probe-mobile
