### ISSUE TITLE
web_connectivity: allow to repeating test for selected URLs

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#69] opened 2017-03-03 16:20 UTC
User story: I am a user of the app, I have seen anomalies for a specific set of URLs, there is one URL that I am really surprised to see showing an anomaly, and I want to re-run the test for such URL only, to understand whether we're talking about a transient error or a real anomaly.

xref: https://github.com/TheTorProject/ooniprobe-ios/issues/99

**Comment by lorenzoPrimi** [comment] 2019-01-17 03:48
duplicate of https://github.com/ooni/probe/issues/801

**Closed by lorenzoPrimi** 2019-01-17 03:48 UTC
Labels: question, usability, wishlist
